In [1]:
import numpy as np
import torch

In [3]:
array = np.array([1,5,8,9])
tensor = torch.from_numpy(array)
array,tensor,tensor.shape

(array([1, 5, 8, 9]), tensor([1, 5, 8, 9]), torch.Size([4]))

In [5]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor, numpy_tensor.shape, tensor.shape

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 (7,),
 torch.Size([7]))