<a href="https://colab.research.google.com/github/Darunesh1/Deep_Learning/blob/main/week_1/tensor_creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
print(f"{np.__version__}")

1.26.4


In [3]:
scalar_tensor = torch.tensor(7)

vector_tensor = torch.tensor([1,2,3,4,5])

matrix_tensor = torch.tensor([
    [1,2,3],
    [2,3,4],
    [8,9,10]
])

### converting numpy array to tensor

In [4]:
np_array = np.array([
    [1,2,3],
    [4,5,6]
])
tensor_numpy= torch.from_numpy(np_array)
print(f"type of the numpy array: {tensor_numpy.dtype}")
print(f"shape of the numpy array: {tensor_numpy.shape}")

type of the numpy array: torch.int64
shape of the numpy array: torch.Size([2, 3])


*  shared memory

In [5]:
np_array[0,0]=55
tensor_numpy

tensor([[55,  2,  3],
        [ 4,  5,  6]])

### some functions to fill the tesor with values

In [6]:
zero_tensor = torch.zeros(3,3)
one_tensor = torch.ones(1,6)
empty_tensor = torch.empty(4,4)
# static values
some_value =  torch.full((5,6),88)

In [7]:
print(zero_tensor)
print(one_tensor)
print(empty_tensor)
print(some_value)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1., 1., 1., 1.]])
tensor([[4.3298e-10, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [2.7606e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [4.7514e-10, 0.0000e+00, 2.7606e-43, 0.0000e+00],
        [2.7606e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[88, 88, 88, 88, 88, 88],
        [88, 88, 88, 88, 88, 88],
        [88, 88, 88, 88, 88, 88],
        [88, 88, 88, 88, 88, 88],
        [88, 88, 88, 88, 88, 88]])


In [8]:
vector =  torch.tensor([1,2,3])

diagonal_vector = torch.diag(vector)

print(vector)
print(diagonal_vector)

tensor([1, 2, 3])
tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])


In [9]:
dia =  torch.diag(diagonal_vector)
print(dia)

tensor([1, 2, 3])
