<a href="https://colab.research.google.com/github/Darunesh1/Deep_Learning/blob/main/week_1/tensor_creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import torch
import numpy as np

In [10]:
print(f"{np.__version__}")

2.4.2


In [6]:
scalar_tensor = torch.tensor(7)

vector_tensor = torch.tensor([1,2,3,4,5])

matrix_tensor = torch.tensor([
    [1,2,3],
    [2,3,4],
    [8,9,10]
])

### converting numpy array to tensor

In [18]:
np_array = np.array([
    [1,2,3],
    [4,5,6]
])
tensor_numpy= torch.from_numpy(np_array)
print(f"type of the numpy array: {tensor_numpy.dtype}")
print(f"shape of the numpy array: {tensor_numpy.shape}")

RuntimeError: Numpy is not available

*  shared memory

In [8]:
np_array[0,0]=55
tensor_numpy

NameError: name 'tensor_numpy' is not defined

### some functions to fill the tesor with values

In [11]:
zero_tensor = torch.zeros(3,3)
one_tensor = torch.ones(1,6)
empty_tensor = torch.empty(4,4)
# static values
some_value =  torch.full((5,6),88)

In [12]:
print(zero_tensor)
print(one_tensor)
print(empty_tensor)
print(some_value)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1., 1., 1., 1.]])
tensor([[2.0811e-15, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[88, 88, 88, 88, 88, 88],
        [88, 88, 88, 88, 88, 88],
        [88, 88, 88, 88, 88, 88],
        [88, 88, 88, 88, 88, 88],
        [88, 88, 88, 88, 88, 88]])


In [17]:
vector =  torch.tensor([1,2,3])

diagonal_vector = torch.diag(vector)

print(vector)
print(diagonal_vector)

tensor([1, 2, 3])
tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])
