<a href="https://colab.research.google.com/github/Darunesh1/Deep_Learning/blob/main/week_1/tensor_creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
scalar_tensor = torch.tensor(7)

vector_tensor = torch.tensor([1,2,3,4,5])

matrix_tensor = torch.tensor([
    [1,2,3],
    [2,3,4],
    [8,9,10]
])

### converting numpy array to tensor

In [ ]:
np_array = np.array([
    [1,2,3],
    [4,5,6]
])
tensor_numpy= torch.from_numpy(np_array)
print(f"type of the numpy array: {tensor_numpy.dtype}")
print(f"shape of the numpy array: {tensor_numpy.shape}")

type of the numpy array: torch.int64
shape of the numpy array: torch.Size([2, 3])


*  shared memory

In [ ]:
np_array[0,0]=55
tensor_numpy

tensor([[55,  2,  3],
        [ 4,  5,  6]])

### some functions to fill the tesor with values

In [ ]:
zero_tensor = torch.zeros(3,3)
one_tensor = torch.ones(1,6)
empty_tensor = torch.empty(4,4)
# static values
some_value =  torch.full((5,6),88)

In [ ]:
print(zero_tensor)
print(one_tensor)
print(empty_tensor)
print(some_value)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1., 1., 1., 1.]])
tensor([[1.4476e+27, 4.3150e-41, 6.9717e-09, 0.0000e+00],
        [2.6011e-14, 4.3150e-41, 2.6028e-14, 4.3150e-41],
        [1.3563e-19, 6.4600e+19, 2.0319e-43, 0.0000e+00],
        [5.2577e-09, 0.0000e+00, 1.4476e+27, 4.3150e-41]])
tensor([[88, 88, 88, 88, 88, 88],
        [88, 88, 88, 88, 88, 88],
        [88, 88, 88, 88, 88, 88],
        [88, 88, 88, 88, 88, 88],
        [88, 88, 88, 88, 88, 88]])
